// Blackbox declaration for synthesis (Yosys).
// Matches the macro generated by OpenRAM for FreePDK45 (see sram_config_freepdk45.py).
// Do NOT synthesize this module's internals - physical layout comes from
// freepdk45_sram_32x256_1rw1r.lef/.gds, timing from freepdk45_sram_32x256_1rw1r.lib.
(* blackbox *)
module freepdk45_sram_32x256_1rw1r (
`ifdef USE_POWER_PINS
    vdd,
    gnd,
`endif
    clk0, csb0, web0, addr0, din0, dout0,
    clk1, csb1, addr1, dout1
);

  parameter DATA_WIDTH = 32;
  parameter ADDR_WIDTH = 8;

`ifdef USE_POWER_PINS
  inout vdd;
  inout gnd;
`endif

  input                     clk0;
  input                     csb0;
  input                     web0;
  input  [ADDR_WIDTH-1:0]   addr0;
  input  [DATA_WIDTH-1:0]   din0;
  output [DATA_WIDTH-1:0]   dout0;

  input                     clk1;
  input                     csb1;
  input  [ADDR_WIDTH-1:0]   addr1;
  output [DATA_WIDTH-1:0]   dout1;

endmodule
